dependencies:
  build:
    - python:3.8.2

build_targets:
  - name: release
    commands:
      - python3 -m pip install --user --upgrade setuptools wheel twine
      - python3 setup.py sdist bdist_wheel
      - python3 -m twine upload --non-interactive dist/*
  - name: demo
    commands:
      - python demo.py
  - name: lint
    commands:
      - pip install black
      - black --check .
  # For integration tests to work locally, you must have access to the
  # proprietary yourbase-python-engine code, and it must be a sibling directory
  # to yourbase-python.
  - name: integration
    build_after:
      - integration_standard
      - integration_pytest
    commands:
      - echo "Integration tests succeeded!"
    host_only: true
  - name: integration_standard
    commands:
      - pip install -r tests/integration/requirements.txt
      - python tests/integration/app.py
    host_only: true
  - name: integration_pytest
    commands:
      - pip install -r tests/integration/pytest/requirements.txt
      - pytest -s tests/integration/pytest/app.py
    host_only: true

ci:
  builds:
    - name: release
      build_target: release
      when: tagged IS true
    - name: lint
      build_target: lint
